#!/bin/bash
autoreconf --force --install
#
## make setup
## On MAC OS X, GNU libtoolize is named 'glibtoolize':
#if [ "`uname -s 2>/dev/null`" == 'Darwin' ]
#then
# glibtoolize
#else
# libtoolize
#fi
#
#aclocal -I m4
#automake --gnu --add-missing --copy --force
#autoheader
#autoconf
#
#pushd restclient-cpp
#./autogen.sh
#popd

exit 0
